version: "3.8"

services:

    # prometheus:
    #   image: prom/prometheus:v2.32.1
    #   ports:
    #   - "9090:9090"

  grafana:
    # TODO: switch to versioned file when updated
    image: grafana/grafana:main
    ports:
    - "3000:3000"

  loki:
    image: grafana/loki:2.4.2
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:2.4.2
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml
      - ./logs/:/app/logs/
      - data-promtail:/promtail_pos/positions.yaml

volumes:
  data-promtail:
